<a href="https://colab.research.google.com/github/Trishti-s/Deep_Learning/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [ ]:
df=pd.read_csv('/content/glass.csv')

In [ ]:
df.head()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,1
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,1
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,1
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,1
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,1


In [ ]:
df.shape

(214, 10)

In [ ]:
df.describe()

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
count,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000,214.000000
mean,1.518365,13.407850,2.684533,1.444907,72.650935,0.497056,8.956963,0.175047,0.057009,2.780374
std,0.003037,0.816604,1.442408,0.499270,0.774546,0.652192,1.423153,0.497219,0.097439,2.103739
min,1.511150,10.730000,0.000000,0.290000,69.810000,0.000000,5.430000,0.000000,0.000000,1.000000
25%,1.516522,12.907500,2.115000,1.190000,72.280000,0.122500,8.240000,0.000000,0.000000,1.000000
50%,1.517680,13.300000,3.480000,1.360000,72.790000,0.555000,8.600000,0.000000,0.000000,2.000000
75%,1.519157,13.825000,3.600000,1.630000,73.087500,0.610000,9.172500,0.000000,0.100000,3.000000
max,1.533930,17.380000,4.490000,3.500000,75.410000,6.210000,16.190000,3.150000,0.510000,7.000000


In [ ]:
X=df.drop('Type',axis=1)
y=df['Type']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y
)


In [ ]:
def sigmoid(self,x):
  return 1/(1+np.exp)

In [ ]:
def feed_forward(self,X):
  z=np.dot(X,self.w)
  h=self.sigmoid(z)
  return(h)

In [ ]:
def error(self,h,y):
  error=(-y*np.log(h)-(1-y)*np.log(1-h)).mean()
  self.E=np.append(self.E,error)


In [ ]:
def backprop(self,X,y,h):
  self.delta_E_w=np.dot(X.T,h-y)/self.outputLayer
  self.w_list.append(self.w)
  self.w=self.w-eta*self.delta_E_w

In [ ]:
def predict(self,X):

  pred=self.feedforward(X)
  return pred

In [ ]:
def classify(self,y):
  return self.predict(y).round()

In [ ]:
def train(self,X,y):
    for epoch in range(epochs):
      h = self.feedforward(X)
      self.backprop(X,y,h)
      self.error(h, y)

In [ ]:
eta = 0.001
epochs=10000
inputLayer=X.shape[1]
outputLayer=1

In [ ]:
iv = ['RI','Mg','Al','K','Ca']
X=df[iv].values

In [ ]:
from sklearn.linear_model import LogisticRegression
SPNN=LogisticRegression(max_iter=1000)
SPNN.fit(X,y)
pred=SPNN.predict(X)
pred_prob=SPNN.predict_proba(X)
print("weight:",SPNN.coef_)

weight: [[ 0.02424417  1.55827653 -1.84133913  0.35731061  0.49055094]
 [-0.00877074  0.54858869  0.34948243  0.80097851  0.49257307]
 [-0.01314321  1.29869667 -0.88563219 -0.65558589  0.40214039]
 [-0.01876506 -0.75319677  1.67736785  1.31327591  0.27025085]
 [-0.01533847 -0.92262374 -0.42966564 -1.82901615 -0.54807543]
 [ 0.03177331 -1.72974138  1.12978668  0.013037   -1.10743982]]
