<a href="https://colab.research.google.com/github/Trishti-s/Deep_Learning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def step_function(x):
  if x>=0:
    return 1
  else:
    return 0

In [4]:
class Perceptron:
  def __init__(self,lr=0.1,epochs=10):
    self.lr=lr
    self.epochs=epochs
    self.weights=None
    self.bias=None

  def fit(self,X,y):
    n_features=X.shape[1]

    self.weights=np.zeros(n_features)
    self.bias=0

    for _ in range(self.epochs):
      for i in range(len(X)):
        linear_output=np.dot(X[i],self.weights)+self.bias
        y_pred=step_function(linear_output)

        error=y[i]-y_pred


        self.weights=self.weights+self.lr*error*X[i]
        self.bias=self.bias+self.lr*error

  def predict(self,X):
      outputs=[]
      for x in X:
          linear_output=np.dot(x,self.weights)+self.bias
          outputs.append(step_function(linear_output))
      return np.array(outputs)

In [5]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [6]:
#and gate
y_and=np.array([0,0,0,1])

p_and=Perceptron()
p_and.fit(X,y_and)

print("AND Gate Output:")
print(p_and.predict(X))

AND Gate Output:
[0 0 0 1]


In [7]:
#or gate
y_or=np.array([0,1,1,1])

p_or=Perceptron()
p_or.fit(X, y_or)

print("OR Gate Output:")
print(p_or.predict(X))

OR Gate Output:
[0 1 1 1]


In [8]:
#nand gate
y_nand=np.array([1,1,1,0])

p_nand=Perceptron()
p_nand.fit(X, y_nand)

print("NAND Gate Output:")
print(p_nand.predict(X))

NAND Gate Output:
[1 1 1 0]


In [9]:
#nor gate
y_nor=np.array([1,0,0,0])

p_nor=Perceptron()
p_nor.fit(X, y_nor)

print("NOR Gate Output:")
print(p_nor.predict(X))

NOR Gate Output:
[1 0 0 0]
